version = 0.1

[default.deploy.parameters]
stack_name = "thf-motion-scan"
resolve_s3 = true
s3_prefix = "thf-motion-scan"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
resolve_image_repos = true
confirm_changeset = false
disable_rollback = false

[default.build.parameters]
cached = true
parallel = true
