# ==============================================================================
# THF Motion Scan - CloudFormation Template
# Purpose: S3→SQS→Lambda→DynamoDB のサーバーレス動画処理基盤
# Architecture: Event-driven processing with SQS buffering
# Decision Log: ADR-007, ADR-008
#
# CRITICAL:
#   - VideosBucket は QueuePolicy に依存（DependsOn: QueuePolicy）
#   - QueuePolicy の Condition は AccountId ベース（循環依存回避、ADR-008）
#   - Lambda には ECR イメージ使用（linux/amd64、ADR-009）
#   - S3 ライフサイクル: videos 30日削除、results 90日Glacier移行
#   - DynamoDB TTL: 90日自動削除
# ==============================================================================

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: THF Motion Scan - AWS Serverless Application

Globals:
  Function:
    Timeout: 900  # 15分（動画処理用）
    MemorySize: 3008  # MediaPipe用に大容量
    Environment:
      Variables:
        RESULTS_BUCKET: !Ref ResultsBucket
        TABLE_NAME: !Ref ResultsTable

Resources:
  # S3バケット: アップロード用
  VideosBucket:
    Type: AWS::S3::Bucket
    DependsOn: QueuePolicy
    Properties:
      BucketName: !Sub 'thf-motion-scan-videos-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter30Days
            Status: Enabled
            ExpirationInDays: 30
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:*
            Queue: !GetAtt ProcessingQueue.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: videos/
                  - Name: suffix
                    Value: .mp4

  # S3バケット: 結果保存用
  ResultsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'thf-motion-scan-results-${AWS::AccountId}'
      LifecycleConfiguration:
        Rules:
          - Id: MoveToGlacierAfter90Days
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER

  # SQSキュー
  ProcessingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: thf-motion-scan-processing-queue
      VisibilityTimeout: 960  # Lambda timeout + バッファ
      MessageRetentionPeriod: 1209600  # 14日
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 3

  # デッドレターキュー
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: thf-motion-scan-dlq
      MessageRetentionPeriod: 1209600  # 14日

  # SQSポリシー（S3からの通知を許可）
  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ProcessingQueue
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: s3.amazonaws.com
            Action:
              - sqs:SendMessage
            Resource: !GetAtt ProcessingQueue.Arn
            Condition:
              StringEquals:
                aws:SourceAccount: !Ref AWS::AccountId

  # Lambda関数
  ProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/thf-motion-scan:latest'
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ProcessingQueue.Arn
            BatchSize: 1
      Policies:
        - S3ReadPolicy:
            BucketName: !Sub 'thf-motion-scan-videos-${AWS::AccountId}'
        - S3CrudPolicy:
            BucketName: !Sub 'thf-motion-scan-results-${AWS::AccountId}'
        - DynamoDBCrudPolicy:
            TableName: !Ref ResultsTable

  # DynamoDBテーブル
  ResultsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: thf-motion-scan-results
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: video_id
          AttributeType: S
        - AttributeName: processed_at
          AttributeType: S
      KeySchema:
        - AttributeName: video_id
          KeyType: HASH
        - AttributeName: processed_at
          KeyType: RANGE
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true

Outputs:
  VideosBucketName:
    Description: "S3バケット名（動画アップロード用）"
    Value: !Ref VideosBucket
    Export:
      Name: !Sub '${AWS::StackName}-VideosBucket'

  ResultsBucketName:
    Description: "S3バケット名（結果保存用）"
    Value: !Ref ResultsBucket
    Export:
      Name: !Sub '${AWS::StackName}-ResultsBucket'

  ProcessingQueueUrl:
    Description: "SQSキューURL"
    Value: !Ref ProcessingQueue
    Export:
      Name: !Sub '${AWS::StackName}-QueueUrl'

  ProcessingFunctionArn:
    Description: "Lambda関数ARN"
    Value: !GetAtt ProcessingFunction.Arn
    Export:
      Name: !Sub '${AWS::StackName}-FunctionArn'

  ResultsTableName:
    Description: "DynamoDBテーブル名"
    Value: !Ref ResultsTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'
